export const NOMES_MOEDAS: { [key: string]: string } = {
    'AFN': 'Afegane Afegão',
    'ETB': 'Birr Etíope',
    'THB': 'Baht Tailandês',
    'PAB': 'Balboa Panamenho',
    'VES': 'Bolívar Venezuelano',
    'BOB': 'Boliviano',
    'GHS': 'Cedi Ganês',
    'CRC': 'Colón Costarriquenho',
    'SVC': 'Colón Salvadorenho',
    'NIO': 'Córdoba Nicaraguense',
    'DKK': 'Coroa Dinamarquesa',
    'ISK': 'Coroa Islandesa',
    'NOK': 'Coroa Norueguesa',
    'SEK': 'Coroa Sueca',
    'CZK': 'Coroa Tcheca',
    'GMD': 'Dalasi Gambiano',
    'DZD': 'Dinar Argelino',
    'KWD': 'Dinar Kuwaitiano',
    'BHD': 'Dinar Bahreinita',
    'IQD': 'Dinar Iraquiano',
    'JOD': 'Dinar Jordaniano',
    'LYD': 'Dinar Líbio',
    'MKD': 'Dinar Macedônio',
    'RSD': 'Dinar Sérvio',
    'SDG': 'Dinar Sudanês',
    'TND': 'Dinar Tunisiano',
    'SSP': 'Dinar Sul-Sudanês',
    'SDR': 'Direitos Especiais de Saque (FMI)',
    'MAD': 'Dirham Marroquino',
    'AED': 'Dirham dos Emirados Árabes Unidos',
    'STN': 'Dobra de São Tomé e Príncipe',
    'AUD': 'Dólar Australiano',
    'BSD': 'Dólar Bahamense',
    'BMD': 'Dólar Bermudense',
    'CAD': 'Dólar Canadense',
    'GYD': 'Dólar Guianense',
    'NAD': 'Dólar Namibiano',
    'BBD': 'Dólar de Barbados',
    'BZD': 'Dólar de Belize',
    'BND': 'Dólar de Brunei',
    'KYD': 'Dólar das Ilhas Cayman',
    'SGD': 'Dólar de Cingapura',
    'CLF': 'Unidade de Fomento Chilena', // Dólar Chileno é CLP, CLF é uma unidade de conta
    'FJD': 'Dólar de Fiji',
    'HKD': 'Dólar de Hong Kong',
    'TTD': 'Dólar de Trinidad e Tobago',
    'XCD': 'Dólar do Caribe Oriental',
    'USD': 'Dólar dos Estados Unidos',
    'JMD': 'Dólar Jamaicano',
    'LRD': 'Dólar Liberiano',
    'NZD': 'Dólar Neozelandês',
    'SBD': 'Dólar das Ilhas Salomão',
    'SRD': 'Dólar Surinamês',
    'VND': 'Dong Vietnamita',
    'AMD': 'Dram Armênio',
    'CVE': 'Escudo Cabo-verdiano',
    'ANG': 'Florim das Antilhas Holandesas',
    'XCG': 'Franco CFA Central (Não oficial - pode ser XAF)', // XAF ou XOF são mais comuns
    'AWG': 'Florim Arubano',
    'HUF': 'Forint Húngaro',
    'CDF': 'Franco Congolês',
    'BIF': 'Franco Burundinês',
    'KMF': 'Franco Comorense',
    'XAF': 'Franco CFA da África Central',
    'XOF': 'Franco CFA da África Ocidental',
    'XPF': 'Franco CFP',
    'DJF': 'Franco Djibutiano',
    'GNF': 'Franco Guineense',
    'MGA': 'Ariary Malgaxe',
    'RWF': 'Franco Ruandês',
    'CHF': 'Franco Suíço',
    'HTG': 'Gourde Haitiano',
    'PYG': 'Guarani Paraguaio',
    'UAH': 'Hryvnia Ucraniana',
    'JPY': 'Iene Japonês',
    'GEL': 'Lari Georgiano',
    'ALL': 'Lek Albanês',
    'HNL': 'Lempira Hondurenha',
    'SLL': 'Leone de Serra Leoa',
    'MDL': 'Leu Moldavo',
    'RON': 'Leu Romeno',
    'BGN': 'Lev Búlgaro',
    'GIP': 'Libra de Gibraltar',
    'EGP': 'Libra Egípcia',
    'GBP': 'Libra Esterlina',
    'FKP': 'Libra das Ilhas Falkland',
    'LBP': 'Libra Libanesa',
    'SHP': 'Libra de Santa Helena',
    'SYP': 'Libra Síria',
    'SZL': 'Lilangeni Suazi',
    'LSL': 'Loti Lesoto',
    'TMT': 'Manat Turcomeno',
    'MZN': 'Metical Moçambicano',
    'ERN': 'Nakfa Eritreia',
    'NGN': 'Naira Nigeriana',
    'AOA': 'Kwanza Angolano',
    'TWD': 'Novo Dólar Taiwanês',
    'TRY': 'Lira Turca',
    'PEN': 'Sol Peruano',
    'BTN': 'Ngultrum Butanês',
    'MRO': 'Ouguiya Mauritana (antigo)',
    'MRU': 'Ouguiya Mauritana',
    'TOP': 'Paʻanga Tonganesa',
    'MOP': 'Pataca de Macau',
    'ARS': 'Peso Argentino',
    'CLP': 'Peso Chileno',
    'COP': 'Peso Colombiano',
    'COU': 'Unidade de Valor Real Colombiana', // Usado para ajuste de dívidas
    'CUP': 'Peso Cubano',
    'DOP': 'Peso Dominicano',
    'PHP': 'Peso Filipino',
    'MXN': 'Peso Mexicano',
    'UYU': 'Peso Uruguaio',
    'BWP': 'Pula Botsuanense',
    'MWK': 'Kwacha Malauiana',
    'ZMW': 'Kwacha Zambiana',
    'GTQ': 'Quetzal Guatemalteco',
    'MMK': 'Kyat de Mianmar',
    'PGK': 'Kina da Papua-Nova Guiné',
    'LAK': 'Kip Laosiano',
    'ZAR': 'Rand Sul-Africano',
    'CNY': 'Yuan Chinês',
    'CNH': 'Yuan Chinês Offshore',
    'QAR': 'Rial Catarense',
    'OMR': 'Rial Omanense',
    'YER': 'Rial Iemenita',
    'IRR': 'Rial Iraniano',
    'SAR': 'Rial Saudita',
    'KHR': 'Riel Cambojano',
    'MYR': 'Ringgit Malaio',
    'RUB': 'Rublo Russo',
    'BYN': 'Rublo Bielorrusso',
    'TJS': 'Somoni Tajique',
    'MUR': 'Rupia Mauriciana',
    'NPR': 'Rupia Nepalesa',
    'SCR': 'Rupia de Seicheles',
    'LKR': 'Rupia do Sri Lanka',
    'INR': 'Rupia Indiana',
    'IDR': 'Rupia Indonésia',
    'MVR': 'Rupia Maldiva',
    'PKR': 'Rupia Paquistanesa',
    'ILS': 'Novo Shekel Israelense',
    'KGS': 'Som Quirguiz',
    'UZS': 'Som Uzbeque',
    'BDT': 'Taka de Bangladesh',
    'WST': 'Tala Samoana',
    'KZT': 'Tenge Cazaque',
    'MNT': 'Tugrik Mongol',
    'VUV': 'Vatu de Vanuatu',
    'KRW': 'Won Sul-Coreano',
    'TZS': 'Xelim Tanzaniano',
    'KES': 'Xelim Queniano',
    'UGX': 'Xelim Ugandense',
    'SOS': 'Xelim Somali',
    'PLN': 'Złoty Polonês',
    'EUR': 'Euro',
    'XAU': 'Ouro (Unidade Troy Ounce)',
    'BRL': 'Real Brasileiro',
};